import numpy as np
from numpy.typing import NDArray

class RecoveryError(Exception): ...

class PreparedBatch:
    @property
    def token(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def candidate_bytes(self) -> NDArray[np.uint8]: ...
    @property
    def lengths(self) -> NDArray[np.uint16]: ...

class BatchCompletion:
    @property
    def checked(self) -> int: ...
    @property
    def matches(self) -> int: ...
    @property
    def completed(self) -> int: ...

type CandidateRecord = tuple[str, str, str, list[str]]

class RecoverySession:
    @staticmethod
    def plan(
        mnemonic_file: str,
        words_file: str,
        fingerprint: str,
        state_dir: str,
        neighbors: int = ...,
        max_replacements: int = ...,
        lowercase_already_tried: bool = ...,
    ) -> RecoverySession: ...
    @staticmethod
    def open(mnemonic_file: str, words_file: str, state_dir: str) -> RecoverySession: ...
    def take_mnemonic_bytes(self) -> NDArray[np.uint8]: ...
    def phase_summaries(self) -> list[tuple[str, int]]: ...
    def neighbor_suggestions(self) -> list[tuple[str, list[tuple[str, int]]]]: ...
    def settings(self) -> tuple[int, int, int, int, bool]: ...
    def target_fingerprint(self) -> str: ...
    def completed(self) -> int: ...
    def has_pending_matches(self) -> bool: ...
    def pending_matches(self) -> list[CandidateRecord]: ...
    def prepare_batch(self, through: str, batch_size: int) -> PreparedBatch | None: ...
    def complete_batch(self, token: int, seeds: NDArray[np.uint8]) -> BatchCompletion: ...
    def fingerprint_batch(self, seeds: NDArray[np.uint8]) -> list[int]: ...
    def sample_batch(self, batch_size: int) -> PreparedBatch: ...
    def enumerate_candidates(
        self, through: str, limit: int, cursor_json: str | None = ...
    ) -> tuple[list[CandidateRecord], str]: ...

def reject_match(state_dir: str, match_id: str) -> None: ...
